services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: oidc_kneox_db
      POSTGRES_USER: justa_kneo
      POSTGRES_PASSWORD: city421
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8572:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: oidc_kneox_db
      DB_USER: justa_kneo
      DB_PASSWORD: city421
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
    ports:
      - "9087:8080"
    depends_on:
      - postgres
    volumes:
      - ./init-scripts:/opt/keycloak/data/import/
    command: ["start-dev", "--import-realm"]

volumes:
  postgres_data:
