version: '3.1'

services:

  db:
    image: postgres:13
    container_name: pg_database_lit_print
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: lit_print_db
      POSTGRES_PASSWORD: 437601
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5434:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - fff

  litprint:
    container_name: lit_print
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 38707:38707
    environment:
      - LITPRINT_DB_HOST=db
      - LITPRINT_DB_HOST_PORT=5432
    networks:
      - fff

networks:
   fff:
     driver: bridge
