---
- hosts: all
  become: yes

  tasks:
    - name: Stop the Keypractica service
      ansible.builtin.systemd:
        name: keypractica
        state: stopped

    - name: Update the Keypractica project from GitHub
      ansible.builtin.git:
        repo: 'https://github.com/Semantyca/Keypractica.git'
        dest: '/home/keypractica/be_server'
        version: master
        force: yes

    - name: Build the project using Maven
      ansible.builtin.shell:
        cmd: '/opt/apache-maven-3.9.3/bin/mvn package -Dquarkus.package.type=uber-jar -DskipTests'
        chdir: '/home/keypractica/be_server'

    - name: Start Keypractica service
      ansible.builtin.systemd:
        name: keypractica
        state: started
