name: Deploy Keypractica

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.HOST_NAME }} >> ~/.ssh/known_hosts

      - name: Ensure core utilities are installed
        run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "apt-get install -y coreutils"

      - name: Ensure Java 21 is installed
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "
            apt-get install -y openjdk-21-jdk
            if ! java -version 2>&1 | grep -q '21'; then
              echo 'Java 21 is not installed. Please install Java 21 and try again.'
              exit 1
            fi
          "

      - name: Ensure Maven is installed
        run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "apt-get install -y maven"

      - name: Stop Keypractica service
        run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "systemctl stop keypractica"

      - name: Update project from GitHub
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "
            cd /home/keypractica/be_server
            git pull origin master
          "

      - name: Set JAVA_HOME environment variable
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "
            echo 'export JAVA_HOME=/usr/lib/jvm/java-21-openjdk' >> /etc/profile
            source /etc/profile
          "
      - name: Build project
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "
            cd /home/keypractica/be_server
            mvn package -Dquarkus.package.type=uber-jar -DskipTests
          "
          env:
            JAVA_HOME: /usr/lib/jvm/java-21-openjdk
            MAVEN_OPTS: "--illegal-access=permit"

      - name: Start Keypractica service
        run: ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.HOST_NAME }} "systemctl start keypractica"

      - name: Check if server is running
        run: |
          for i in {1..5}; do
            if curl -sSf http://api.keypractica.com > /dev/null; then
              echo "Server is running"
              exit 0
            fi
            echo "Attempt $i: Server not yet running, waiting..."
            sleep 10
          done
          echo "Server failed to start"
          exit 1