name: Deploy Keypractica Project

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch.

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: semantyca

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project with Maven
        run: mvn package -Dquarkus.package.type=uber-jar -DskipTests
        env:
          MAVEN_CLI_OPTS: '-s /path/to/settings.xml -B'

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secret.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e  # Exit immediately if a command exits with a non-zero status.
            echo "Starting deployment to server at ${host}"
            echo "Transfer the JAR file to the server"
            scp ${{ github.workspace }}/target/quarkus-keypractica-runner.jar ${username}@${host}:/home/keypractica/be_server/projects/target
            echo "Stopping the Keypractica service"
            sudo systemctl stop keypractica
            echo "Starting the Keypractica service"
            sudo systemctl start keypractica
            echo "Deployment completed successfully"
      - name: Send Message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Hi! The Keypractica backend has been updated"

