name: Deploy Keypractica Project

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Use the latest version of the checkout action.

      - name: Setup Java
        uses: actions/setup-java@v4  # Use the latest version of the setup-java action.
        with:
          java-version: '17'  # Set the Java version to 17.
          distribution: 'temurin'  # Use Temurin as the Java distribution.

      - name: Build Project with Maven
        run: mvn package -Dquarkus.package.type=uber-jar -DskipTests  # Build the project with Maven.
        env:
          MAVEN_CLI_OPTS: '-s /path/to/settings.xml -B'  # Placeholder for Maven CLI options.

      - name: Deploy to Server
        uses: appleboy/ssh-action@master  # Use the SSH action to deploy the built application.
        with:
          host: ${{ secrets.SERVER_HOST }}  # SSH host stored as a secret.
          username: ${{ secrets.SERVER_USERNAME }}  # SSH username stored as a secret.
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH private key stored as a secret.
          script: |
            # Transfer the JAR file to the server.
            scp ${{ github.workspace }}/target/my-application-uber.jar ${username}@${host}:/path/to/deployment/directory
            # Stop the current service.
            sudo systemctl stop keypractica
            # Start the service again, using the new JAR.
            sudo systemctl start keypractica

      - name: Send Message to Telegram
        uses: appleboy/telegram-action@master  # Use the Telegram action to send a notification.
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}  # Telegram chat ID stored as a secret.
          token: ${{ secrets.TELEGRAM_TOKEN }}  # Telegram bot token stored as a secret.
          message: "Hi! The Keypractica backend has been updated"  # Notification message.

