name: Deploy Keypractica Project

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch.
  pull_request:
    branches:
      - master  # Optionally, trigger on pull requests to the master branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project with Maven
        run: mvn package -Dquarkus.package.type=uber-jar -DskipTests
        env:
          MAVEN_CLI_OPTS: '-s /path/to/settings.xml -B'

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            function handle_error {
            echo "ERROR: $1"
            exit 1
            }
            trap 'handle_error "An error occurred on line $LINENO"' ERR
            set -ex  # Print each command to the terminal as it is executed and exit on error
            
            echo "Starting deployment to server at ${{ secrets.SERVER_HOST }}"
            echo "Transfer the JAR file to the server"
            if ! scp -P ${{ secrets.SERVER_PORT }} ${{ github.workspace }}/target/quarkus-keypractica-runner.jar ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/home/keypractica/be_server/projects/target; then
            handle_error "Failed to transfer JAR file"
            fi
            echo "Stopping the Keypractica service"
            if ! sudo systemctl stop keypractica; then
            handle_error "Failed to stop the service"
            fi
            echo "Starting the Keypractica service"
            if ! sudo systemctl start keypractica; then
            handle_error "Failed to start the service"
            fi
            echo "Deployment completed successfully"
            
            - name: Diagnostic Log
        run: |
          echo "Deployment script completed."
          echo "Reviewing system status and recent executions."
          systemctl status keypractica
          journalctl -u keypractica --since "10 minutes ago"

      - name: Send Message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Hi! The Keypractica backend has been updated"
